name: Bump is-kit version

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true

      - name: Get pnpm store directory
        id: pnpm-store-path
        run: echo "dir=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Get latest version from npm
        id: latest
        run: |
          echo "version=$(npm show is-kit version)" >> $GITHUB_OUTPUT

      - name: Get current version from package.json
        id: current
        run: |
          current=$(jq -r '.dependencies["is-kit"]' package.json | sed 's/[^0-9.]//g')
          echo "version=$current" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare
        run: |
          if [ "${{ steps.latest.outputs.version }}" != "${{ steps.current.outputs.version }}" ]; then
            echo "should_update=true" >> $GITHUB_OUTPUT
          else
            echo "should_update=false" >> $GITHUB_OUTPUT
          fi

      - name: Update package.json
        if: steps.compare.outputs.should_update == 'true'
        run: |
          jq '.dependencies["is-kit"] = "^${{ steps.latest.outputs.version }}"' package.json > tmp && mv tmp package.json

      - name: Install dependencies (optional)
        if: steps.compare.outputs.should_update == 'true'
        run: pnpm install --no-frozen-lockfile

      - name: Create PR
        if: steps.compare.outputs.should_update == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: bump is-kit to ^${{ steps.latest.outputs.version }}"
          branch: chore/bump-is-kit-${{ steps.latest.outputs.version }}
          title: "chore: bump is-kit to ^${{ steps.latest.outputs.version }}"
          body: |
            This PR updates is-kit to ^${{ steps.latest.outputs.version }}.
          labels: dependencies
